### ISSUE TITLE
ERROR! no action detected in task

### ISSUE THREAD

**Issue by zxyz** [EggieCode/ansible-role-ufw#1]
Hello,
with ansible 2.3.1.0 the role is not working. 

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in 'tasks/main.yml': line 5, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> ---
> - name: UFW Forward generate IPv4
>   ^ here

I only got rudímentary knowledge of ansible. But it seems to be unhappy with this part

```
- name: "UFW Forward generate IPv4"
  ufw_forward:
    data: "{{ ufw_forwarding }}"
    ipv6: False
  register: ufw_result
```
due to the `ufw_forward` part which is not a known module to ansible.
