### ISSUE TITLE
suggestion: move sysctl stuff from install_debian.yml to main.yml and add contition for protocol family

### ISSUE THREAD

**Issue by zxyz** [EggieCode/ansible-role-ufw#3]
right now forwarding is by default enabled or IPv4 and IPv6 when installing ufw via install_debian.yml task.
I'd like to suggest to make it conditionally if NAT rules for the respective protocol family exist, something like this maybe:

```
- name: "update sysctl forward ipv4"
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ufw_forwarding.0 is defined

- name: update sysctl forward ipv6
  sysctl:
    name: "net.ipv6.conf.all.forwarding"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ufw_forwarding6.0 is defined
```
