### ISSUE TITLE
multiple port forwardings result in multiple MASQUERADE entries

### ISSUE THREAD

**Issue by zxyz** [EggieCode/ansible-role-ufw#4]
the `ufw_forward.py` generates a `MASQUERADE` entry for every port forwarding, also when they use same interface and subnet.

host_var:
```
ufw_forwarding:
  - comment: "SSH VM1"
    incomming_dev: eth0
    outgoing_dev: br0
    outgoing_network: 192.168.1.0/24
    masquerading: True
    conntrack_state: RELATED,ESTABLISHED
    forwards:
     - destination_ip: 192.168.1.2
       destination_port: 22
       incomming_port: 22222
       protocol: tcp
  - comment: "SSH VM2"
    incomming_dev: eth0
    outgoing_dev: br0
    outgoing_network: 192.168.1.0/24
    masquerading: True
    conntrack_state: RELATED,ESTABLISHED
    forwards:
     - destination_ip: 192.168.1.3
       destination_port: 22
       incomming_port: 33333
       protocol: tcp
```

output of `POSTROUTING` chain
```
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1        0     0 MASQUERADE  all  --  *      eth0     192.168.1.0/24       0.0.0.0/0           
2        0     0 MASQUERADE  all  --  *      eth0     192.168.1.0/24       0.0.0.0/0 
```
